"""Reading .bib entries, including the ones that do not fit on one line."""

from bibfile import Entry, entries, fields_of

# DBLP wraps every author list and most titles. A line-anchored parser reports
# this entry as having no author at all, which is how a correct bibliography
# gets flagged as broken.
DBLP_WRAPPED = """@inproceedings{rusch2021,
  author       = {T. Konstantin Rusch and
                  Siddhartha Mishra},
  title        = {Coupled Oscillatory Recurrent Neural Network (coRNN): An accurate
                  and (gradient) stable architecture for learning long time dependencies},
  booktitle    = {9th International Conference on Learning Representations, {ICLR} 2021,
                  Virtual Event, Austria, May 3-7, 2021},
  publisher    = {OpenReview.net},
  year         = {2021},
}
"""


def test_wrapped_author_is_found_whole():
    fields = fields_of(DBLP_WRAPPED)
    assert fields["author"] == "T. Konstantin Rusch and Siddhartha Mishra"


def test_wrapped_title_keeps_its_nested_braces_contents():
    fields = fields_of(DBLP_WRAPPED)
    assert fields["title"].startswith("Coupled Oscillatory Recurrent Neural Network (coRNN)")
    assert "long time dependencies" in fields["title"]


def test_nested_braces_do_not_end_the_value_early():
    # `{ICLR}` protects capitalisation; a naive scan stops at its closing brace
    assert "{ICLR} 2021" in fields_of(DBLP_WRAPPED)["booktitle"]
    assert fields_of(DBLP_WRAPPED)["booktitle"].endswith("May 3-7, 2021")


def test_entry_identity():
    (entry,) = entries(DBLP_WRAPPED)
    assert (entry.kind, entry.key) == ("inproceedings", "rusch2021")


def test_quoted_and_bare_values():
    fields = fields_of('@article{k,\n  title = "Quoted",\n  year = 1975,\n}')
    assert fields == {"title": "Quoted", "year": "1975"}


def test_a_commented_out_field_is_not_a_field():
    # the provenance comments carry text that looks exactly like a field
    text = "@misc{k,\n  % cited in the manuscript as: title = {Not This}\n  year = {2020},\n}"
    assert fields_of(text) == {"year": "2020"}


def test_labels_come_from_the_provenance_comment():
    text = "@misc{k,\n  year = {2020},\n  % cited in the manuscript as: coRNN; Rusch 2021\n}"
    (entry,) = entries(text)
    assert entry.labels == "coRNN; Rusch 2021"


def test_entries_are_returned_in_file_order():
    text = "@misc{a,\n year={1}\n}\n\n@misc{b,\n year={2}\n}\n"
    assert [e.key for e in entries(text)] == ["a", "b"]


def test_leading_header_comments_are_not_an_entry():
    assert entries("% a header\n% and more\n\n@misc{a,\n year={1}\n}\n") == [
        Entry("misc", "a", {"year": "1"}, "@misc{a,\n year={1}\n}\n")
    ]


def test_an_unbalanced_entry_yields_what_it_can_rather_than_hanging():
    assert fields_of("@misc{k,\n  title = {never closed\n")["title"] == "never closed"


# A comment cannot live INSIDE an entry — BibTeX treats it as a syntax error —
# so the provenance comments sit on the line before `@`. Splitting on `@` alone
# hands each one to the previous entry.
# note the blank line between comment and entry — that is how the generators
# actually write these files, and it is what makes the comment look like the
# tail of the PREVIOUS entry to anything splitting on `@`
TWO_WITH_COMMENTS = """% cited as: RON

@misc{ceni2024,
  year = {2024},
}

% cited in the manuscript as: coRNN; Rusch 2021

@inproceedings{rusch2021,
  year = {2021},
}
"""


def test_a_leading_comment_belongs_to_the_entry_it_introduces():
    first, second = entries(TWO_WITH_COMMENTS)
    assert (first.key, first.labels) == ("ceni2024", "RON")
    assert (second.key, second.labels) == ("rusch2021", "coRNN; Rusch 2021")


def test_a_raw_block_ends_at_its_own_closing_brace():
    first, _ = entries(TWO_WITH_COMMENTS)
    assert first.raw.rstrip().endswith("}")
    assert "rusch2021" not in first.raw


def test_the_older_comment_spelling_is_still_read():
    (entry,) = entries("% cited as: LSM\n\n@article{maass2002,\n  year = {2002},\n}\n")
    assert entry.labels == "LSM"


def test_a_file_header_is_not_attributed_to_the_first_entry():
    # the header precedes every entry and belongs to none of them
    text = ("% Bibliography for 01-evidence-audit\n%\n% Generated by ...\n\n"
            "@misc{a,\n  year = {2020},\n}\n")
    (entry,) = entries(text)
    assert entry.labels == ""
    assert "Bibliography for" not in entry.raw


def test_a_trailing_comment_does_not_drift_further_each_rewrite():
    # the failure this guards: parse, re-emit each raw block, parse again.
    # If the comment rides on the previous entry it moves one entry per round.
    text = TWO_WITH_COMMENTS
    for _ in range(3):
        text = "\n\n".join(e.raw.rstrip() for e in entries(text)) + "\n"
        assert [(e.key, e.labels) for e in entries(text)] == [
            ("ceni2024", "RON"), ("rusch2021", "coRNN; Rusch 2021")]
